### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by mmueller-xyz** [TGM-HIT/latex-protocol#9]
please make a Makefile, which passes the arguments to the python file, so you can run ``make``

**Comment by re1** [comment]
The files name is indeed ambiguous but might fit the purpose here. Alternatively I came up with the following options: 

``` sh
tex
make
build
run
main
```

**Comment by KevinW1998** [comment]
`build` would be the best alternative here

**Comment by re1** [comment]
> `build` would be the best alternative here

4 months later the problem popped up somewhere else. A `build` script might be confused with the `build/` directory. Also it is a bit long.

**Comment by mborko** [comment]
I will change it to maketex.
